### ISSUE TITLE
Load and save Task list to file 

### ISSUE THREAD

**Issue by danieltanyi** [danieltanyi/IP#9]
- [ ]FileOutputStream fos= new FileOutputStream("/Users/tmp-sda-1160/eclipse- 
- [ ] ObjectOutputStream oos= new ObjectOutputStream(fos);
- [ ] workspace/IP/src/test.txt");
